{% set version = "0.6.0" %}

package:
  name: obake
  version: {{ version }}

source:
  url: https://github.com/bluescarni/obake/archive/v{{ version }}.tar.gz
  sha256: e45c33c73ecaf6716f7959274625a0705725047389cdf2388241b52965305434

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - clang      # [win]
    - ninja      # [win]

outputs:

  - name: obake
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - clang      # [win]
        - ninja      # [win]
      host:
        - abseil-cpp
        - tbb-devel
        - mppp
        - boost-cpp
        - backtrace    # [linux]
      run:
        - backtrace    # [linux]
    files:
      - lib/libobake*{{ SHLIB_EXT }}   # [not win]
      - lib/libobake.so.*              # [linux]
      - lib/libobake.*.dylib           # [osx]
      - Library/bin/obake.dll          # [win]
    test:
      commands:
        - test -f $PREFIX/lib/libobake.so                                     # [linux]
        - test -f $PREFIX/lib/libobake.dylib                                  # [osx]
        - if not exist %PREFIX%\\Library\\bin\\obake.dll exit 1               # [win]

  - name: obake-devel
    build:
      run_exports:
        # SO name changes at minor rev bumps.
        - {{ pin_subpackage('obake', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
        - {{ pin_compatible('tbb', max_pin=None) }}
        - {{ pin_compatible('mppp', max_pin="x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - clang      # [win]
        - ninja      # [win]
      host:
        - abseil-cpp
        - tbb-devel
        - mppp
        - boost-cpp
        - backtrace    # [linux]
      run:
        - abseil-cpp
        - tbb-devel
        - boost-cpp
        - backtrace    # [linux]
        - {{ pin_subpackage("obake", exact=True) }}
    files:
      - include/obake            # [not win]
      - lib/cmake/obake          # [not win]
      - Library/include/obake    # [win]
      - Library/lib/obake.lib    # [win]
      - Library/lib/cmake/obake  # [win]
    test:
      commands:
        - test -f $PREFIX/include/obake/config.hpp                            # [unix]
        - if not exist %PREFIX%\\Library\\include\\obake\\config.hpp exit 1   # [win]
        - if not exist %PREFIX%\\Library\\lib\\obake.lib exit 1               # [win]

about:
  home: https://bluescarni.github.io/obake/
  license: MPL-2.0
  license_file: LICENSE
  summary: A C++17 library for the symbolic manipulation of sparse polynomials and other closely-related mathematical objects

extra:
  recipe-maintainers:
    - bluescarni
