{% set version = "0.9.0" %}

package:
  name: obake
  version: {{ version }}

source:
  url: https://github.com/bluescarni/obake/archive/v{{ version }}.tar.gz
  sha256: 2f265632b5e203d242862b3515390c78efb70367b1088224d2a900b54f132b93

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make       # [unix]
    - clang      # [win]
    - ninja      # [win]

outputs:

  - name: obake
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make       # [unix]
        - clang      # [win]
        - ninja      # [win]
      host:
        - fmt
        - libboost-headers
        - tbb-devel
        - mppp
        - backtrace    # [linux]
      run:
        - backtrace    # [linux]
    files:
      - lib/libobake*{{ SHLIB_EXT }}   # [not win]
      - lib/libobake.so.*              # [linux]
      - lib/libobake.*.dylib           # [osx]
      - Library/bin/obake.dll          # [win]
    test:
      commands:
        - test -f $PREFIX/lib/libobake.so                                     # [linux]
        - test -f $PREFIX/lib/libobake.dylib                                  # [osx]
        - if not exist %PREFIX%\\Library\\bin\\obake.dll exit 1               # [win]

  - name: obake-devel
    build:
      run_exports:
        # SO name changes at minor rev bumps.
        - {{ pin_subpackage('obake', max_pin='x.x') }}
        - {{ pin_compatible('tbb', max_pin=None) }}
        - {{ pin_compatible('mppp', max_pin="x.x") }}
        - {{ pin_compatible('fmt', max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make       # [unix]
        - clang      # [win]
        - ninja      # [win]
      host:
        - libboost-devel
        - tbb-devel
        - mppp
        - fmt
        - backtrace    # [linux]
      run:
        # boost version compatibility is taken care of by run-export from host;
        # this just ensures presence of headers & metadata
        - libboost-devel
        - tbb-devel
        - backtrace    # [linux]
        - {{ pin_subpackage("obake", exact=True) }}
    files:
      - include/obake            # [not win]
      - lib/cmake/obake          # [not win]
      - Library/include/obake    # [win]
      - Library/lib/obake.lib    # [win]
      - Library/lib/cmake/obake  # [win]
    test:
      commands:
        - test -f $PREFIX/include/obake/config.hpp                            # [unix]
        - if not exist %PREFIX%\\Library\\include\\obake\\config.hpp exit 1   # [win]
        - if not exist %PREFIX%\\Library\\lib\\obake.lib exit 1               # [win]

about:
  home: https://bluescarni.github.io/obake/
  license: MPL-2.0
  license_file: LICENSE
  summary: A C++20 library for the symbolic manipulation of sparse polynomials and other closely-related mathematical objects

extra:
  recipe-maintainers:
    - bluescarni
